folio-org/folio-custom-fields

pom.xml
=> FCFIELDS-1 folio-custom-fields: Update to RMB v31.x

PERSONAL_DATA_DISCLOSURE.md
Place a copy of the personal data disclosure form at the top level of the module github repository to disclose stored types of personal data
* add PERSONAL_DATA_DISCLOSURE.md file
=> FCFIELDS-16  Add personal data disclosure form

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/repository/CustomFieldsRepositoryImpl.java, src/main/java/org/folio/spring/ApplicationConfig.java
=> FCFIELDS-14 Upgrade to RMB 32.1

pom.xml
Log4j vulnerability verification and correction
=> FCFIELDS-21 Log4j vulnerability verification and correction

NEWS.md, pom.xml
- Update dependencies
- Update NEWS
https://issues.folio.org/browse/FCFIELDS-29
=> FCFIELDS-29 RMB v35 upgrade

CODEOWNERS
The purpose of this PR is to update the codeowners file.
=> [FCFIELDS-39] - Updated the CODEOWNERS file.

pom.xml
Upgrade the folio-di-support module so that it uses Java 17 and can let mod-users use this latest versions of the modules.
Update the version in pom.xml
=> [FCFIELDS-40] - Upgrade the folio-di-support version.

pom.xml
Update the folio-di-support in the pom.xml
Update the version in pom.xml
=> FCFIELDS-40 - Update the folio-di-support in the pom.xml

NEWS.md, pom.xml
Release: Poppy - Folio-custom-fields (FCFIELDS)
Followed release steps.
=> FCFIELDS-41 - Release: Poppy - Folio-custom-fields (FCFIELDS)

pom.xml, src/test/java/org/folio/validate/CustomFieldValue.java
To Upgrade raml and vertex version for Q release.
To Upgrade raml and vertex version for Q release.
=> [FCFIELDS-51] - Upgrade rmb and vertex version

NEWS.md, pom.xml
=> FCFIELDS-50 - Release 2.0.0 for Q

NEWS.md, pom.xml
To upgrade the spring version based on latest release.
=> [FCFIELDS-50] - Upgrade the versions in pom.xml file

NEWS.md, pom.xml
=> FCFIELDS-50 - Release 2.1.0

.github/workflows/postgres.yml, pom.xml
=> [FCFIELDS-55] - Upgrade rmb version to 35.3.0

NEWS.md, pom.xml
=> [FCFIELDS-56] - Ramsons release

.github/workflows/postgres.yml, Jenkinsfile, pom.xml, src/main/java/org/folio/repository/CustomFieldsRepository.java, src/main/java/org/folio/repository/CustomFieldsRepositoryImpl.java, src/main/java/org/folio/service/CustomFieldsServiceImpl.java
https://folio-org.atlassian.net/browse/FOLIO-4230
=> FOLIO-4230: Java and vertex version upgrade

src/main/java/org/folio/service/CustomFieldsServiceImpl.java
=> Added logs for debugging

pom.xml
=> Fix master branch from 2.3.1-SNAPSHOT to 2.4.0-SNAPSHOT

src/main/java/org/folio/service/CustomFieldsServiceImpl.java
Run replaceAll process as single transaction.
=> FCFIELDS-61: replaceAll: remove values in transaction

src/main/java/org/folio/repository/CustomFieldsConstants.java, src/main/java/org/folio/repository/CustomFieldsRepositoryImpl.java
https://folio-org.atlassian.net/browse/FCFIELDS-62
Fix SQL injection.
Remove vulnerable SQL code.
Don't use %s in SQL code if possible, use $1 placeholders that are save.
=> FCFIELDS-62: Remove SQL injection "WHERE id='%s'"

NEWS.md, pom.xml, src/main/java/org/folio/repository/CustomFieldsConstants.java, src/main/java/org/folio/repository/CustomFieldsRepositoryImpl.java, src/main/java/org/folio/service/CustomFieldsServiceImpl.java
https://folio-org.atlassian.net/browse/FCFIELDS-64
=> Sunflower Bugfest release 2.3.1
